# Generated by Django 5.1.6 on 2025-05-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerConfiguracion',
            fields=[
                ('IDRedSocial', models.IntegerField(db_column='IDRedSocial', help_text='ID de la Red Social', primary_key=True, serialize=False)),
                ('IDSender', models.CharField(blank=True, db_column='IDSender', max_length=50, null=True)),
                ('marca_id', models.IntegerField(blank=True, db_column='marca_id', default=1, null=True)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('Token', models.CharField(blank=True, db_column='Token', help_text='Token', max_length=255, null=True)),
                ('TokenHook', models.CharField(blank=True, db_column='TokenHook', max_length=50, null=True)),
                ('urlHook', models.CharField(blank=True, db_column='urlHook', max_length=100, null=True)),
                ('urlApi', models.CharField(blank=True, db_column='urlApi', help_text='urlApi', max_length=100, null=True)),
                ('logo', models.CharField(blank=True, db_column='logo', max_length=150, null=True)),
                ('Estado', models.IntegerField(blank=True, db_column='Estado', default=1, help_text='Estado', null=True)),
            ],
            options={
                'verbose_name_plural': 'Messenger Configuracion',
                'db_table': 'MessengerConfiguracion',
            },
        ),
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('IDChat', models.AutoField(db_column='IDChat', primary_key=True, serialize=False)),
                ('IDRedSocial', models.IntegerField(db_column='IDRedSocial', default=1)),
                ('IDSender', models.CharField(blank=True, db_column='IDSender', max_length=50, null=True)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('Avatar', models.CharField(blank=True, db_column='Avatar', max_length=100, null=True)),
                ('IDEL', models.IntegerField(blank=True, db_column='IDEL', help_text='ID estado', null=True)),
                ('IDSubEstadoLead', models.IntegerField(blank=True, db_column='IDSubEstadoLead', help_text='ID sub estado', null=True)),
                ('nuevos_mensajes', models.IntegerField(blank=True, db_column='nuevos_mensajes', default=0)),
                ('Estado', models.IntegerField(blank=True, db_column='Estado', default=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Messenger Chats',
                'db_table': 'Messenger',
                'unique_together': {('IDChat', 'IDRedSocial')},
            },
        ),
        migrations.CreateModel(
            name='MessengerMensaje',
            fields=[
                ('IDChatMensaje', models.AutoField(db_column='IDChatMensaje', help_text='Id del Mensaje', primary_key=True, serialize=False)),
                ('IDChat', models.IntegerField(verbose_name='ID del Chat')),
                ('IDSender', models.CharField(blank=True, db_column='IDSender', max_length=50, null=True)),
                ('Mensaje', models.CharField(blank=True, db_column='Mensaje', help_text='Mensaje', max_length=2000, null=True)),
                ('Fecha', models.CharField(blank=True, db_column='Fecha', help_text='Fecha del Mensaje', max_length=50, null=True)),
                ('Hora', models.CharField(blank=True, db_column='Hora', help_text='Hora del Mensaje', max_length=50, null=True)),
                ('Url', models.CharField(blank=True, db_column='Url', max_length=150, null=True)),
                ('Extencion', models.CharField(blank=True, db_column='Extencion', max_length=200, null=True)),
                ('Estado', models.IntegerField(blank=True, db_column='Estado', default=1, help_text='1: enviado, 2: recibido, 3: visto', null=True)),
            ],
            options={
                'verbose_name_plural': 'Messenger mensajes',
                'db_table': 'MessengerMensaje',
                'unique_together': {('IDChatMensaje', 'IDChat')},
            },
        ),
    ]
