# Generated by Django 5.1.6 on 2025-05-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengermensaje',
            name='IDChat',
            field=models.IntegerField(verbose_name='ID del Chat'),
        ),
    ]
