# Generated by Django 5.1.6 on 2025-05-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerconfiguracion',
            name='marca_id',
            field=models.CharField(blank=True, db_column='marca_id', max_length=50, null=True),
        ),
    ]
