# Generated by Django 5.1.6 on 2025-06-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerconfiguracion',
            name='openai',
            field=models.BooleanField(default=False),
        ),
    ]
