# Generated by Django 5.1.6 on 2025-05-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLead',
            fields=[
                ('IDEL', models.AutoField(db_column='IDEL', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('Color', models.CharField(blank=True, db_column='Color', max_length=20, null=True)),
                ('IDEstado', models.IntegerField(blank=True, db_column='IDEstado', null=True)),
            ],
            options={
                'db_table': 'EstadoLead',
            },
        ),
        migrations.CreateModel(
            name='SubEstadoLead',
            fields=[
                ('IDSubEstadoLead', models.AutoField(db_column='IDSubEstadoLead', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=150, null=True)),
                ('IDEstado', models.IntegerField(blank=True, db_column='IDEstado', null=True)),
                ('IDEL', models.ForeignKey(db_column='IDEL', on_delete=django.db.models.deletion.CASCADE, related_name='subestados', to='messenger.estadolead')),
            ],
            options={
                'db_table': 'SubEstadoLead',
            },
        ),
    ]
