# Generated by Django 5.1.6 on 2025-05-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_estadolead_subestadolead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messengerconfiguracion',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='messengerconfiguracion',
            name='Template',
        ),
        migrations.AddField(
            model_name='messengerconfiguracion',
            name='logo',
            field=models.CharField(blank=True, db_column='logo', max_length=150, null=True),
        ),
    ]
