# Generated by Django 5.1.6 on 2025-05-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_messengerconfiguracion_marca_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messengerconfiguracion',
            name='marca_id',
        ),
    ]
