# Generated by Django 5.1.6 on 2025-05-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_remove_messengerconfiguracion_marca_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerconfiguracion',
            name='marca_id',
            field=models.IntegerField(blank=True, db_column='marca_id', default=1, null=True),
        ),
    ]
