# Generated by Django 5.1.6 on 2025-05-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_remove_messengerconfiguracion_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subestadolead',
            name='Color',
            field=models.CharField(blank=True, db_column='Color', max_length=20, null=True),
        ),
    ]
