# Generated by Django 5.1.6 on 2025-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_subestadolead_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='messenger',
            name='nuevos_mensajes',
            field=models.IntegerField(db_column='Nuevos mensajes', default=0),
        ),
    ]
