# Generated by Django 5.1.6 on 2025-05-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_messengerconfiguracion_marca_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerplantilla',
            name='tipo',
            field=models.IntegerField(blank=True, db_column='tipo', default=0, help_text='0: default, 2: entrada, 3: salida'),
        ),
    ]
