# Generated by Django 5.1.6 on 2025-06-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_messenger_openai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger',
            name='Nombre',
            field=models.CharField(blank=True, db_column='Nombre', max_length=100, null=True),
        ),
    ]
