# Generated by Django 5.1.6 on 2025-05-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_messengerplantilla_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messengerplantilla',
            options={'verbose_name': 'Respuesta automática', 'verbose_name_plural': 'Respuestas automáticas'},
        ),
        migrations.AlterField(
            model_name='messengerplantilla',
            name='tipo',
            field=models.IntegerField(blank=True, db_column='tipo', default=0, help_text='0: default, 1: entrada, 2: salida'),
        ),
    ]
