# Generated by Django 5.1.6 on 2025-07-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_messenger_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerconfiguracion',
            name='openai_analizador',
            field=models.BooleanField(default=True),
        ),
    ]
