# Generated by Django 5.1.6 on 2025-07-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_rename_urlhook_messengerconfiguracion_url_graph_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengerconfiguracion',
            name='url_graph_v',
            field=models.CharField(blank=True, db_column='url_graph_v', max_length=100, null=True),
        ),
    ]
