# Generated by Django 5.1.6 on 2025-07-16 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_alter_messengerconfiguracion_url_graph_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='messenger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messengermensaje',
            name='user_id',
            field=models.IntegerField(blank=True, db_column='user_id', null=True),
        ),
    ]
