# Generated by Django 5.1.6 on 2025-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_messenger_nuevos_mensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger',
            name='nuevos_mensajes',
            field=models.IntegerField(blank=True, db_column='nuevos_mensajes', default=0),
        ),
    ]
