# Generated by Django 5.1.6 on 2025-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_messenger_created_at_messengermensaje_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerconfiguracion',
            name='enviar_quien_escribio',
            field=models.BooleanField(default=False),
        ),
    ]
