# Generated by Django 5.1.6 on 2025-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_messengerconfiguracion_enviar_quien_escribio'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerconfiguracion',
            name='responder_automaticamente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messengerconfiguracion',
            name='responder_automaticamente_minutos',
            field=models.IntegerField(db_column='responder_automaticamente_minutos', default=5),
        ),
    ]
