# Generated by Django 5.1.6 on 2025-05-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('IDNivel', models.AutoField(db_column='IDNivel', primary_key=True, serialize=False)),
                ('IDNivelPadre', models.IntegerField(blank=True, db_column='IDNivelPadre', null=True)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=150, null=True)),
                ('Descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('Color', models.CharField(blank=True, db_column='Color', max_length=40, null=True)),
                ('URLImagen', models.CharField(blank=True, db_column='URLImagen', max_length=150, null=True)),
                ('Nivel', models.IntegerField(blank=True, db_column='Nivel', help_text='nivel 1 al 8', null=True)),
                ('NivelFinal', models.IntegerField(db_column='NivelFinal', default=0)),
                ('IDEstado', models.IntegerField(db_column='IDEstado', default=1)),
            ],
            options={
                'verbose_name_plural': 'Niveles',
                'db_table': 'niveles',
            },
        ),
        migrations.CreateModel(
            name='WhatsappConfiguracion',
            fields=[
                ('IDRedSocial', models.AutoField(db_column='IDRedSocial', help_text='ID de la Red Social', primary_key=True, serialize=False)),
                ('marca_id', models.IntegerField(db_column='marca_id')),
                ('Telefono', models.CharField(blank=True, db_column='Telefono', help_text='Telefono Asociado a la Red Social', max_length=20, null=True)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('Token', models.CharField(blank=True, db_column='Token', help_text='Token', max_length=255, null=True)),
                ('TokenHook', models.CharField(blank=True, db_column='TokenHook', help_text='TokenHook', max_length=50, null=True)),
                ('urlHook', models.CharField(blank=True, db_column='urlHook', max_length=100, null=True)),
                ('urlApi', models.CharField(blank=True, db_column='urlApi', help_text='urlApi', max_length=100, null=True)),
                ('Template', models.CharField(blank=True, db_column='Template', max_length=100, null=True)),
                ('Language', models.CharField(blank=True, db_column='Language', max_length=40, null=True)),
                ('logo', models.CharField(blank=True, db_column='logo', max_length=150, null=True)),
                ('Estado', models.IntegerField(db_column='Estado', default=1, help_text='Estado del telefono asociado')),
            ],
            options={
                'verbose_name_plural': 'WhatsApp Configuracion',
                'db_table': 'whatsapp_configuracion',
            },
        ),
        migrations.CreateModel(
            name='WhatsappMetaPlantillas',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('lenguaje', models.CharField(blank=True, db_column='lenguaje', max_length=40, null=True)),
                ('estado', models.IntegerField(db_column='estado', default=1)),
            ],
            options={
                'verbose_name_plural': 'WhatsApp Meta Plantillas',
                'db_table': 'whatsapp_meta_plantillas',
            },
        ),
        migrations.CreateModel(
            name='ChatNiveles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDChat', models.IntegerField(db_column='IDChat')),
                ('IDNivel', models.IntegerField(db_column='IDNivel')),
            ],
            options={
                'verbose_name_plural': 'Chat Niveles',
                'db_table': 'chat_niveles',
                'unique_together': {('IDChat', 'IDNivel')},
            },
        ),
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('IDChat', models.AutoField(db_column='IDChat', primary_key=True, serialize=False)),
                ('IDRedSocial', models.IntegerField(db_column='IDRedSocial', default=1)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('Telefono', models.CharField(blank=True, db_column='Telefono', max_length=50, null=True)),
                ('FechaUltimaPlantilla', models.DateTimeField(blank=True, db_column='FechaUltimaPlantilla', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('Avatar', models.CharField(blank=True, db_column='Avatar', max_length=100, null=True)),
                ('IDEL', models.IntegerField(blank=True, db_column='IDEL', help_text='ID lead estado', null=True)),
                ('IDSubEstadoLead', models.IntegerField(blank=True, db_column='IDSubEstadoLead', null=True)),
                ('nuevos_mensajes', models.IntegerField(blank=True, db_column='nuevos_mensajes', default=0)),
                ('Estado', models.IntegerField(blank=True, db_column='Estado', default=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'WhatsApp Chats',
                'db_table': 'whatsapp',
                'unique_together': {('IDChat', 'IDRedSocial')},
            },
        ),
        migrations.CreateModel(
            name='WhatsappMensajes',
            fields=[
                ('IDChatMensaje', models.AutoField(db_column='IDChatMensaje', help_text='Id del Mensaje', primary_key=True, serialize=False)),
                ('IDChat', models.IntegerField(help_text='ID del Chat', verbose_name='ID del Chat')),
                ('Telefono', models.CharField(blank=True, db_column='Telefono', help_text='Telefono del Emisor/Receptor del Mensaje', max_length=50, null=True)),
                ('Mensaje', models.CharField(blank=True, db_column='Mensaje', help_text='Mensaje', max_length=2000, null=True)),
                ('Fecha', models.CharField(blank=True, db_column='Fecha', help_text='Fecha del Mensaje', max_length=50, null=True)),
                ('Hora', models.CharField(blank=True, db_column='Hora', help_text='Hora del Mensaje', max_length=50, null=True)),
                ('Url', models.CharField(blank=True, db_column='Url', max_length=150, null=True)),
                ('Extencion', models.CharField(blank=True, db_column='Extencion', max_length=200, null=True)),
                ('Estado', models.IntegerField(blank=True, db_column='Estado', default=1, help_text='Estado del mensaje, 1: enviado, 2: recibido, 3: visto', null=True)),
            ],
            options={
                'verbose_name_plural': 'WhatsApp mensajes',
                'db_table': 'whatsapp_mensajes',
                'unique_together': {('IDChatMensaje', 'IDChat')},
            },
        ),
    ]
