# Generated by Django 5.1.6 on 2025-06-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsapp_openai_whatsappmensajes_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp',
            name='openai',
            field=models.BooleanField(default=True),
        ),
    ]
