# Generated by Django 5.1.6 on 2025-07-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_alter_whatsapp_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfiguracion',
            name='openai_analizador',
            field=models.BooleanField(default=True),
        ),
    ]
