# Generated by Django 5.1.6 on 2025-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_whatsappconfiguracion_openai_analizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmetaplantillas',
            name='media_url',
            field=models.CharField(blank=True, db_column='media_url', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmetaplantillas',
            name='tipo',
            field=models.CharField(blank=True, db_column='tipo', max_length=40, null=True),
        ),
    ]
