# Generated by Django 5.1.6 on 2025-07-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_whatsappmetaplantillas_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmetaplantillas',
            name='mensaje',
            field=models.CharField(blank=True, db_column='mensaje', max_length=1000, null=True),
        ),
    ]
