# Generated by Django 5.1.6 on 2025-07-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_whatsappmetaplantillas_nombre_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmetaplantillas',
            name='usuario_index',
            field=models.CharField(db_column='usuario_index', default=1),
        ),
    ]
