# Generated by Django 5.1.6 on 2025-07-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_whatsappmetaplantillas_usuario_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmetaplantillas',
            name='usuario_index',
            field=models.IntegerField(blank=True, db_column='usuario_index', null=True),
        ),
    ]
