# Generated by Django 5.1.6 on 2025-07-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_alter_whatsappmetaplantillas_usuario_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappconfiguracion',
            old_name='urlHook',
            new_name='url_graph_v',
        ),
    ]
