# Generated by Django 5.1.6 on 2025-07-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0012_rename_urlhook_whatsappconfiguracion_url_graph_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconfiguracion',
            name='url_graph_v',
            field=models.CharField(blank=True, db_column='url_graph_v', max_length=100, null=True),
        ),
    ]
