# Generated by Django 5.1.6 on 2025-07-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0014_whatsappplantillaresumen_origen_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappplantillaresumen',
            name='enviados',
            field=models.IntegerField(blank=True, db_column='enviados', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappplantillaresumen',
            name='exitosos',
            field=models.IntegerField(blank=True, db_column='exitosos', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappplantillaresumen',
            name='fallidos',
            field=models.IntegerField(blank=True, db_column='fallidos', null=True),
        ),
    ]
