# Generated by Django 5.1.6 on 2025-07-15 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0016_whatsappconfiguracionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappplantillaresumen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappplantillaresumen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
