# Generated by Django 5.1.6 on 2025-07-16 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0017_whatsappplantillaresumen_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappmensajes',
            name='user_id',
            field=models.IntegerField(blank=True, db_column='user_id', null=True),
        ),
    ]
