# Generated by Django 5.1.6 on 2025-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0018_whatsapp_created_at_whatsappmensajes_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfiguracion',
            name='enviar_quien_escribio',
            field=models.BooleanField(default=False),
        ),
    ]
