# Generated by Django 5.1.6 on 2025-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0019_whatsappconfiguracion_enviar_quien_escribio'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmetaplantillas',
            name='variables_obligatorio',
            field=models.CharField(blank=True, db_column='variables_obligatorio', max_length=50, null=True),
        ),
    ]
