# Generated by Django 5.1.6 on 2025-07-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0020_whatsappmetaplantillas_variables_obligatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmetaplantillas',
            name='marca_id',
            field=models.IntegerField(db_column='marca_id', default=1),
            preserve_default=False,
        ),
    ]
