# Generated by Django 5.1.6 on 2025-07-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0021_whatsappmetaplantillas_marca_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappProfileAccepts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perfil_id', models.IntegerField()),
                ('accepts', models.CharField(blank=True, db_column='accepts', max_length=800, null=True)),
            ],
            options={
                'verbose_name_plural': 'WhatsApp Perfil Acepta',
                'db_table': 'whatsapp_perfil_acepta',
            },
        ),
    ]
