# Generated by Django 5.1.6 on 2025-07-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0022_whatsappprofileaccepts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(blank=True, db_column='fecha_registro', null=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, db_column='fecha_asignacion', null=True)),
                ('codigo_solicitud', models.CharField(blank=True, db_column='codigo_solicitud', max_length=50, null=True)),
                ('medio_captacion', models.CharField(blank=True, db_column='medio_captacion', max_length=200, null=True)),
                ('marca', models.CharField(blank=True, db_column='marca', max_length=100, null=True)),
                ('nombre_lead', models.CharField(blank=True, db_column='nombre_lead', max_length=255, null=True)),
                ('usuario_asignado', models.CharField(blank=True, db_column='usuario_asignado', max_length=100, null=True)),
                ('monto_solicitado', models.DecimalField(blank=True, db_column='monto_solicitado', decimal_places=2, max_digits=10, null=True)),
                ('celular', models.CharField(blank=True, db_column='celular', max_length=20, null=True)),
                ('propiedad_registros_publicos', models.BooleanField(blank=True, db_column='propiedad_registros_publicos', null=True)),
                ('ocurrencia', models.CharField(blank=True, db_column='ocurrencia', max_length=255, null=True)),
                ('condicion', models.CharField(blank=True, db_column='condicion', max_length=200, null=True)),
                ('tipo_garantia', models.CharField(blank=True, db_column='tipo_garantia', max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, db_column='departamento', max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, db_column='provincia', max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, db_column='distrito', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='WhatsapChatUser',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('IDChat', models.IntegerField(db_column='IDChat')),
                ('user_id', models.IntegerField(db_column='user_id')),
            ],
            options={
                'verbose_name': 'WhatsApp Chat Usuario',
                'verbose_name_plural': 'WhatsApp Chats Usuarios',
                'db_table': 'whatsapp_chat_users',
            },
        ),
    ]
