# Generated by Django 5.1.6 on 2025-07-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0026_whatsappmensajes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp',
            name='respuesta_generada_openai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whatsappmensajes',
            name='origen',
            field=models.IntegerField(blank=True, db_column='origen', default=1, help_text='1:enviados, 2: recibidos, 3: openai', null=True),
        ),
    ]
