# Generated by Django 5.1.6 on 2025-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0027_whatsapp_respuesta_generada_openai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp',
            name='fecha_agenda',
            field=models.DateTimeField(blank=True, db_column='fecha_agenda', null=True),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='user_id_agenda',
            field=models.IntegerField(blank=True, db_column='user_id_agenda', null=True),
        ),
    ]
