# Generated by Django 5.1.6 on 2025-07-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0028_whatsapp_fecha_agenda_whatsapp_user_id_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp',
            name='fecha_proxima_plantilla',
            field=models.DateTimeField(blank=True, db_column='fecha_proxima_plantilla', null=True),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='user_id_proxima_plantilla',
            field=models.IntegerField(blank=True, db_column='user_id_proxima_plantilla', null=True),
        ),
    ]
