# Generated by Django 5.1.6 on 2025-07-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0029_whatsapp_fecha_proxima_plantilla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfiguracion',
            name='envio_lead_n_chat',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='whatsappconfiguracion',
            name='responder_automaticamente_minutos',
            field=models.IntegerField(default=5),
        ),
    ]
