# Generated by Django 5.1.6 on 2025-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0030_whatsappconfiguracion_envio_lead_n_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmetaplantillas',
            name='cliente_index',
            field=models.IntegerField(blank=True, db_column='cliente_index', null=True),
        ),
    ]
