# Generated by Django 5.1.6 on 2025-07-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0031_whatsappmetaplantillas_cliente_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp',
            name='template_name',
            field=models.IntegerField(blank=True, db_column='template_name', null=True),
        ),
    ]
