# Generated by Django 5.1.6 on 2025-07-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0032_whatsapp_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp',
            name='template_params',
            field=models.CharField(blank=True, db_column='template_params', max_length=400, null=True),
        ),
    ]
