# Generated by Django 5.1.6 on 2025-07-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0033_whatsapp_template_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp',
            name='template_name',
            field=models.CharField(blank=True, db_column='template_name', max_length=150, null=True),
        ),
    ]
