# Generated by Django 5.1.6 on 2025-07-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0034_alter_whatsapp_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp',
            name='codigo_solicitud',
            field=models.CharField(blank=True, db_column='codigo_solicitud', max_length=50, null=True),
        ),
    ]
