# Generated by Django 5.1.6 on 2025-07-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0035_whatsapp_codigo_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='codigo',
            field=models.CharField(blank=True, db_column='codigo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='codigo_solicitud',
            field=models.CharField(blank=True, db_column='codigo_solicitud', max_length=100, null=True),
        ),
    ]
