# Generated by Django 5.1.6 on 2025-07-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0036_lead_codigo_alter_lead_codigo_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsapp',
            name='codigo_solicitud',
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='codigo_lead',
            field=models.CharField(blank=True, db_column='codigo_lead', max_length=50, null=True),
        ),
    ]
