# Generated by Django 5.1.6 on 2025-07-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0037_remove_whatsapp_codigo_solicitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsapp',
            name='codigo_lead',
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='lead_id',
            field=models.CharField(blank=True, db_column='lead_id', max_length=50, null=True),
        ),
    ]
