# Generated by Django 5.1.6 on 2025-07-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0038_remove_whatsapp_codigo_lead_whatsapp_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp',
            name='lead_id',
            field=models.IntegerField(blank=True, db_column='lead_id', null=True),
        ),
    ]
