# Generated by Django 5.1.6 on 2025-07-31 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0039_alter_whatsapp_lead_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsapChatUserHistorial',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('IDChat', models.IntegerField(db_column='IDChat')),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_chat_user_id', models.ForeignKey(db_column='whatsapp_chat_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='chat_users', to='whatsapp.whatsapchatuser')),
            ],
            options={
                'verbose_name': 'WhatsApp Chat Usuario Historial',
                'verbose_name_plural': 'WhatsApp Chats Usuarios Historial',
                'db_table': 'whatsapp_chat_users_historial',
            },
        ),
    ]
