# Generated by Django 5.1.6 on 2025-08-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0040_whatsapchatuserhistorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp',
            name='lead_reasignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracion',
            name='reasignar_lead',
            field=models.IntegerField(default=8, help_text='Reasignar lead después de 8 minutos de inactividad del cliente'),
        ),
        migrations.AlterField(
            model_name='whatsappconfiguracion',
            name='contactar_leads',
            field=models.BooleanField(default=False, help_text='Numero para recibir lead'),
        ),
        migrations.AlterField(
            model_name='whatsappconfiguracion',
            name='envio_lead_n_chat',
            field=models.IntegerField(default=3, help_text='Analizar chat después 3 mensajes recibidos'),
        ),
    ]
