# Generated by Django 5.1.6 on 2025-08-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0041_whatsapp_lead_reasignado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappconfiguracion',
            name='reasignar_lead',
        ),
        migrations.AddField(
            model_name='whatsapchatuserhistorial',
            name='lead_reasignado_visto',
            field=models.BooleanField(default=False),
        ),
    ]
