# Generated by Django 5.1.6 on 2025-05-30 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLead',
            fields=[
                ('IDEL', models.AutoField(db_column='IDEL', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('Color', models.CharField(blank=True, db_column='Color', max_length=20, null=True)),
                ('IDEstado', models.IntegerField(blank=True, db_column='IDEstado', default=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estados',
                'db_table': 'EstadoLead',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='MessengerPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, max_length=2000, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('extension', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('tipo', models.IntegerField(blank=True, db_column='tipo', default=0, help_text='0: default, 1: entrada, 2: salida')),
                ('marca_id', models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.PROTECT, related_name='plantillas', to='redes_sociales.marca')),
            ],
            options={
                'verbose_name': 'Respuesta automática',
                'verbose_name_plural': 'Respuestas automáticas',
                'db_table': 'messenger_plantillas',
            },
        ),
        migrations.CreateModel(
            name='SubEstadoLead',
            fields=[
                ('IDSubEstadoLead', models.AutoField(db_column='IDSubEstadoLead', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=150, null=True)),
                ('Color', models.CharField(blank=True, db_column='Color', max_length=20, null=True)),
                ('IDEstado', models.IntegerField(blank=True, db_column='IDEstado', default=1, null=True)),
                ('IDEL', models.ForeignKey(db_column='IDEL', on_delete=django.db.models.deletion.CASCADE, related_name='subestados', to='redes_sociales.estadolead')),
            ],
            options={
                'verbose_name_plural': 'Sub Estados',
                'db_table': 'SubEstadoLead',
            },
        ),
    ]
