# Generated by Django 5.1.6 on 2025-06-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_sociales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadolead',
            name='red_social',
            field=models.IntegerField(blank=True, db_column='red_social', default=1, help_text='1: Messenger, 2: Whatsapp'),
        ),
        migrations.AddField(
            model_name='messengerplantilla',
            name='red_social',
            field=models.IntegerField(blank=True, db_column='red_social', default=1, help_text='1: Messenger, 2: Whatsapp'),
        ),
        migrations.AddField(
            model_name='subestadolead',
            name='red_social',
            field=models.IntegerField(blank=True, db_column='red_social', default=1, help_text='1: Messenger, 2: Whatsapp'),
        ),
    ]
