# Generated by Django 5.1.6 on 2025-06-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_sociales', '0002_estadolead_red_social_messengerplantilla_red_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadolead',
            name='red_social',
            field=models.IntegerField(blank=True, db_column='red_social', default=1, help_text='1: Messenger, 2: Whatsapp, 3: Chat Interno'),
        ),
        migrations.AlterField(
            model_name='messengerplantilla',
            name='red_social',
            field=models.IntegerField(blank=True, db_column='red_social', default=1, help_text='1: Messenger, 2: Whatsapp, 3: Chat Interno'),
        ),
        migrations.AlterField(
            model_name='subestadolead',
            name='red_social',
            field=models.IntegerField(blank=True, db_column='red_social', default=1, help_text='1: Messenger, 2: Whatsapp, 3: Chat Interno'),
        ),
    ]
