# Generated by Django 5.1.6 on 2025-07-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_sociales', '0003_alter_estadolead_red_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadolead',
            name='IDRedSocial',
            field=models.IntegerField(blank=True, db_column='IDRedSocial', help_text='0: Chat Interno, 1+: IDRedSocial', null=True),
        ),
        migrations.AddField(
            model_name='estadolead',
            name='id_crm',
            field=models.IntegerField(blank=True, db_column='id_crm', help_text='id externo', null=True),
        ),
        migrations.AddField(
            model_name='subestadolead',
            name='id_crm',
            field=models.IntegerField(blank=True, db_column='id_crm', help_text='id externo', null=True),
        ),
    ]
