# Generated by Django 5.1.6 on 2025-07-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_sociales', '0004_estadolead_idredsocial_estadolead_id_crm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subestadolead',
            name='IDRedSocial',
            field=models.IntegerField(blank=True, db_column='IDRedSocial', help_text='0: Chat Interno, 1+: IDRedSocial', null=True),
        ),
    ]
