# Generated by Django 5.1.6 on 2025-06-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInternoConfiguracion',
            fields=[
                ('IDRedSocial', models.IntegerField(db_column='IDRedSocial', help_text='ID de la Red Social', primary_key=True, serialize=False)),
                ('marca_id', models.IntegerField(blank=True, db_column='marca_id', default=1, null=True)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('logo', models.CharField(blank=True, db_column='logo', max_length=150, null=True)),
                ('Estado', models.IntegerField(blank=True, db_column='Estado', default=1, help_text='Estado', null=True)),
                ('permitir_archivos', models.BooleanField(default=True, help_text='Permitir envío de archivos')),
            ],
            options={
                'verbose_name_plural': 'Chat Interno Configuracion',
                'db_table': 'chat_interno_configuracion',
            },
        ),
        migrations.CreateModel(
            name='ChatInterno',
            fields=[
                ('IDChat', models.AutoField(db_column='IDChat', primary_key=True, serialize=False)),
                ('IDRedSocial', models.IntegerField(db_column='IDRedSocial', default=1)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('Avatar', models.CharField(blank=True, db_column='Avatar', max_length=100, null=True)),
                ('IDEL', models.IntegerField(blank=True, db_column='IDEL', help_text='ID estado', null=True)),
                ('IDSubEstadoLead', models.IntegerField(blank=True, db_column='IDSubEstadoLead', help_text='ID sub estado', null=True)),
                ('Estado', models.IntegerField(blank=True, db_column='Estado', default=1, null=True)),
                ('tipo_chat', models.IntegerField(choices=[(1, 'Individual'), (2, 'Grupo')], default=1, help_text='Tipo de chat')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del chat/grupo', max_length=500, null=True)),
                ('creado_por', models.IntegerField(db_column='creado_por')),
            ],
            options={
                'verbose_name_plural': 'Chat Interno Chats',
                'db_table': 'chat_interno',
                'unique_together': {('IDChat', 'IDRedSocial')},
            },
        ),
        migrations.CreateModel(
            name='ChatInternoMensaje',
            fields=[
                ('IDChatMensaje', models.AutoField(db_column='IDChatMensaje', help_text='Id del Mensaje', primary_key=True, serialize=False)),
                ('IDChat', models.IntegerField(verbose_name='ID del Chat')),
                ('IDSender', models.CharField(blank=True, db_column='IDSender', max_length=50, null=True)),
                ('Mensaje', models.CharField(blank=True, db_column='Mensaje', help_text='Mensaje', max_length=2000, null=True)),
                ('Fecha', models.CharField(blank=True, db_column='Fecha', help_text='Fecha del Mensaje', max_length=50, null=True)),
                ('Hora', models.CharField(blank=True, db_column='Hora', help_text='Hora del Mensaje', max_length=50, null=True)),
                ('Url', models.CharField(blank=True, db_column='Url', max_length=150, null=True)),
                ('Extencion', models.CharField(blank=True, db_column='Extencion', max_length=200, null=True)),
                ('Estado', models.IntegerField(choices=[(1, 'Enviado'), (2, 'Entregado'), (3, 'Leído'), (4, 'Eliminado')], db_column='Estado', default=1)),
                ('editado', models.BooleanField(default=False, help_text='Mensaje editado')),
                ('fecha_edicion', models.DateTimeField(blank=True, help_text='Fecha de última edición', null=True)),
            ],
            options={
                'verbose_name_plural': 'Chat Interno mensajes',
                'db_table': 'chat_interno_mensaje',
                'unique_together': {('IDChatMensaje', 'IDChat')},
            },
        ),
        migrations.CreateModel(
            name='ChatInternoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Miembro', 'Miembro')], default='Miembro', max_length=40)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('nuevos_mensajes', models.IntegerField(blank=True, db_column='nuevos_mensajes', default=0)),
                ('chat_interno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_detalle', to='chat_interno.chatinterno')),
            ],
            options={
                'verbose_name_plural': 'Chat Interno Miembros',
                'db_table': 'chat_interno_miembro',
                'unique_together': {('chat_interno_id', 'user_id')},
            },
        ),
    ]
