# Generated by Django 5.1.6 on 2025-06-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinternomiembro',
            name='nombre',
            field=models.CharField(blank=True, db_column='nombre', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatinterno',
            name='Nombre',
            field=models.CharField(blank=True, db_column='Nombre', max_length=100, null=True),
        ),
    ]
