# Generated by Django 5.1.6 on 2025-06-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interno', '0002_chatinternomiembro_nombre_alter_chatinterno_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatinternomiembro',
            name='nombre',
        ),
    ]
