# Generated by Django 5.1.6 on 2025-07-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interno', '0004_delete_chatinternoconfiguracion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatinterno',
            unique_together=set(),
        ),
    ]
