# Generated by Django 5.1.6 on 2025-05-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('co_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('no_perfil', models.CharField(max_length=255)),
                ('nc_perfil', models.CharField(max_length=255)),
                ('in_estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='PerfilPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perfil_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'perfil_permissions',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('co_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('co_compania', models.IntegerField()),
                ('co_sede', models.IntegerField()),
                ('co_persona', models.IntegerField(blank=True, null=True)),
                ('co_perfil', models.IntegerField()),
                ('prefijo', models.CharField(blank=True, max_length=10, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('co_ultimo_menu', models.IntegerField(blank=True, null=True)),
                ('no_iniciales', models.CharField(blank=True, max_length=10, null=True)),
                ('nu_celular_trabajo', models.CharField(blank=True, max_length=20, null=True)),
                ('has_chats', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('remember_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_app', models.CharField(blank=True, max_length=255, null=True)),
                ('token_app', models.CharField(blank=True, max_length=255, null=True)),
                ('co_usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('fe_usuario_modifica', models.DateTimeField(blank=True, null=True)),
                ('in_estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserTokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_tokens',
            },
        ),
    ]
