# Generated by Django 5.1.6 on 2025-05-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfiles_perfilpermissions_permissions_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfiles',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='perfilpermissions',
            options={'verbose_name': 'Perfil Permiso', 'verbose_name_plural': 'Perfil Permisos'},
        ),
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usertokens',
            options={'verbose_name': 'Usuario Token', 'verbose_name_plural': 'Usuario Tokens'},
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='nc_perfil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='no_perfil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='co_compania',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='co_perfil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='co_sede',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
