# Generated by Django 5.1.6 on 2025-05-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_perfiles_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
