# Generated by Django 5.1.6 on 2025-07-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('acceso_id', models.CharField(db_column='acceso_id', max_length=8, primary_key=True, serialize=False)),
                ('acceso', models.CharField(blank=True, db_column='acceso', max_length=150, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
                'db_table': 'accesos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccesoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_id', models.IntegerField(db_column='perfil_id')),
                ('acceso_id', models.ForeignKey(db_column='acceso_id', on_delete=django.db.models.deletion.PROTECT, to='users.acceso')),
            ],
            options={
                'verbose_name': 'Acceso Perfil',
                'verbose_name_plural': 'Accesos Perfiles',
                'db_table': 'acceso_perfiles',
                'managed': True,
                'unique_together': {('acceso_id', 'perfil_id')},
            },
        ),
    ]
