# Generated by Django 5.1.6 on 2025-07-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_acceso_accesoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='icono',
            field=models.CharField(blank=True, db_column='icono', max_length=50, null=True),
        ),
    ]
