# Generated by Django 5.1.6 on 2025-07-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_acceso_icono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilPermissions',
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
