# Generated by Django 5.1.6 on 2025-07-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_perfilpermissions_delete_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='openai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='responder_automaticamente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='responder_automaticamente_minutos',
            field=models.IntegerField(default=5),
        ),
    ]
